### ISSUE TITLE
Allow users to close submenu accordions on mobile menu

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2172] opened 2018-07-09 14:44 UTC
**What we're after:** The mega menus use an accordion interaction in mobile view, when the menu is accessible via the hamburger icon. Currently a plus sign turns into a minus sign when one clicks to open the menu. However the minus symbol to close the accordion does not work. In order to improve the usability of the mobile menu, we need to make it so that when a user clicks the icon the menu is properly closed. 

Beyond that, following U.S. design principles, we should also enable the entire row, so that selecting anywhere on that header, a user can successfully close the accordion. 

**Completion criteria:**
- [ ] Make the entire submenu header/bar clickable to that users can select anywhere on that row to close the accordion

![mega_ux](https://user-images.githubusercontent.com/5572856/42457428-73ac32a8-8365-11e8-888e-06793d21d2f8.gif)

**Comment by JonellaCulmer** [comment] 2018-07-09 17:20
@johnnyporkchops Is it possible to make it so the minus signs can close an accordion? When we use the accordion feature on other parts of the site, such as on data tables, selecting the minus sign does close those accordions. I think I'd prefer that that functionality be consistently applied in the mobile menu as well.

**Comment by johnnyporkchops** [comment] 2018-07-10 03:28
USWDS Accordion:
https://designsystem.digital.gov/components/accordions/
For more reference:
https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

**Comment by johnnyporkchops** [comment] 2018-07-10 22:53
@JonellaCulmer, I agree with your comments above. Lets pair on this to  groom this issue more and determine how much of a lift it will be.

**Comment by JonellaCulmer** [comment] 2018-07-11 18:35
@johnnyporkchops Great! I'll add it to 6.5 work so we don't lose track of it.

**Comment by AmyKort** [comment] 2018-07-16 18:52
@JonellaCulmer  can you take a crack at updating this ticket?

**Comment by lbeaufort** [comment] 2019-10-29 21:20
@johnnyporkchops I can't reproduce this issue, can you?

**Comment by JonellaCulmer** [comment] 2019-10-31 20:33
I can't either, but it reminded me of another problem I found. 

https://github.com/fecgov/fec-cms/issues/3313

**Comment by patphongs** [comment] 2020-10-20 17:25
I am able to collapse the accordions on mobile. I will close this ticket, we'll re-prioritize #3313 somewhere to fix it.

**Closed by patphongs** 2020-10-20 17:25 UTC
Labels: Needs prioritization, Work: Front-end
