### ISSUE TITLE
Broken links in AO 2012-20

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1820] opened 2018-02-28 20:34 UTC
In the Request for AO 2012-20, we have some links to audio files that seem to have broken. We need to make these audio files accessible again. https://www.fec.gov/files/legal/aos/2012-20/1209199.pdf (Scroll to the bottom of the pdf to see the links)

Links:
Request from Markwayne Mullin – CD-Rom
Exhibits
http://www.fec.gov/audio/2012/Mullin_Winter_Tulsa_60.mp3
http://www.fec.gov/audio/2012/Mullin_Spring_12_TUL.mp3
http://www.fec.gov/audio/2012/Deck4_2012_04_21_07_00_00_093.mp3

**Comment by lbeaufort** [comment] 2018-03-15 15:38
@AmyKort should this be assigned to someone, or maybe bumped to 5.3?

**Comment by AmyKort** [comment] 2018-03-15 16:06
This is a classic issue, I believe. I think @PaulClark2 reached out to @patphongs  about this? It can move to 5.3.

**Comment by patphongs** [comment] 2018-03-15 16:17
Thanks for the reminder. Haven’t had time to fully diagnose this yet, but I suspect those audio files in this AO could be missing. Will give an update soon...

**Comment by patphongs** [comment] 2018-08-21 19:37
It appears that the audio recordings are not within our records. I'm not sure if it's because it's been named something different, since our audio recordings have this naming convention `yyyy-mm-dd-item#`.mp3. I've reached out to info to see if they have the recordings and can point me in the right direction.

**Comment by patphongs** [comment] 2018-08-23 16:15
Info has informed me that they also do not have copies of the missing recordings. It might still be with someone from OGC, but no one is sure.

**Comment by dorothyyeager** [comment] 2019-03-27 16:20
OGC reached out today to @jjonesfec to resolve this particular issue. They confirmed that they don't have copies of the mp3s in question. 

When I click the links to the mp3s in the last page of this file: https://saos.fec.gov/aodocs/1209199.pdf#page=17 - I noticed that the error message that comes up refers to needing to log in to a website to view those files.

Also the last page refers to a CD-ROM submission with those mp3s.

**Comment by AmyKort** [comment] 2019-04-25 13:22
We're having some difficulty locating these files. I'm moving this ticket to blocked until that problem is resolved.

**Closed** 2019-12-10 16:43 UTC
Labels: Bug
