### ISSUE TITLE
Missing "mailto" email for AO results

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3080] opened 2019-07-26 19:20 UTC
Missing `mailto:` link for missing AO's when you try to click "Email our team": https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=F&ao_requestor=nonexistantrequestor

**Comment by pkfec** [comment] 2019-08-02 20:10
It appears that `mailto` is broken not only on `AO search` but also in `Statues search` and in `All Legal search`.  The `contact_email` variable is defined in base.py. This variable is not accessible in jinja templates unless its defined in `TEMPLATES` dictionary inside `base.py`. it appears that `contact_email` is a duplicate of `webmanager_email`. 

On further research `webmanager_email` is used in other HTML files. And this variable is already defined in the `TEMPLATES` dictionary and is accessible from jinja templates.

Updated the ao, legal docs and legal search JINJA templates to use the webmanager_email variable.
PR ready for review

**Closed** 2019-08-08 19:54 UTC
Labels: Bug
