### ISSUE TITLE
OGC review of language Committee type descriptions

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4673] opened 2021-06-02 14:55 UTC
**What we're after:**
We need to send the draft language for the committee snapshot to OGC for their review. Hopefully, there's a happy place between what's OGC-accurate and simple clear language that doesn't require footnotes and complicated jargon. 

If you need to pair with Jonella on how to get this point across to OGC please reach out. She will make time for you. 

### Related issues
- #4672

### Completion criteria
- [ ] Language is finalized and shared with front-end for development

**Comment by kathycarothers** [comment] 2021-06-08 12:56
This is a duplicate of #4672

**Closed by kathycarothers** 2021-06-08 12:56 UTC
Labels: Pairing opportunity, Work: Content, Work: UX/Design
