### ISSUE TITLE
Website returning 504 error

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/fec-cms#2910] opened 2019-05-20 12:38 UTC
On 5/19/19 around 4:45 am accessing www.fec.gov giving the following error:

```
504 ERROR

The request could not be satisfied.

CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. 
If you received this error while trying to use an app or access a website, please contact the provider or website owner for assistance. 
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by following steps in the CloudFront documentation (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-504-gateway-timeout.html). 
Generated by cloudfront (CloudFront)
Request ID: 2sILIATH-HC4KiJ6fgogFMuv-1lcOgdG6REbIcEJN4JI6oxXh8j0gA==
```

The reason I check www.fec.gov because I am getting lot of **newrelic** alerts:

<img width="300"  src=https://user-images.githubusercontent.com/20324717/58021223-5e972880-7ad8-11e9-9fb5-e9302f37248a.png><img width="300" src=https://user-images.githubusercontent.com/20324717/58021474-f6951200-7ad8-11e9-9198-c0b784e5ae42.png>

** Directly calling api.open.fec.gov returning results **
** Kibana CMS and API log files did not show any obvious errors **

API umbrella is showing following error codes

![image](https://user-images.githubusercontent.com/20324717/58021810-fea18180-7ad9-11e9-9831-ac72cb3fad9f.png)

** Not quite sure this is API or CMS specific issue.  Website start to function normally after 5/19/19 6:00 am.

![image](https://user-images.githubusercontent.com/20324717/58022003-7c658d00-7ada-11e9-8d95-1ecaed8cd6be.png)

**Comment by jason-upchurch** [comment] 2019-05-20 16:46
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-504-gateway-timeout.html

**Comment by jason-upchurch** [comment] 2019-05-21 21:52
Submitted email inquiry to cloud.gov

**Comment by jason-upchurch** [comment] 2019-05-22 17:11
CloudFront does not currently maintain logs. Need to check kibana to see if the logs offer any clues.

**Comment by jason-upchurch** [comment] 2019-05-28 14:31
We are investigating the possibility that this issue was caused by a Tenable scan.

**Comment by jason-upchurch** [comment] 2019-06-03 15:59
Moving to Sprint 9.2 as discussion is ongoing.

**Comment by jason-upchurch** [comment] 2019-06-05 21:04
Investigating app scheduling relative to actual scan.

**Comment by jason-upchurch** [comment] 2019-06-13 17:32
Next scan 6/19/2019, moving to Sprint 9.3 to gather information resulting from the scan.

**Comment by jason-upchurch** [comment] 2019-06-21 19:49
## Closing Summary ##
Overnight tenable scans over the evenings of April 18/19 and May 18/19 are correlated with website outages. Scans over these two evens appeared to target the `proxy` and `cms` `cf.app` in `prod` `cf.space`. 

Over the 24-hour period of May 19, (a Sunday) 91.5 % of the traffic was generated by the Tenable scan.

It was noted during this investigation that all Tenable scan settings were default. During the course of the inquiry, additional debugging logs were enabled on the Tenable scan.

After following up on the June 18/19 scan, it was noted that the website did not experience outage. However, it was determined that the scan itself was aborted due to an unexpected problem. 

This issue is being closed and the July 18/19 scan will be tracked under Review website status after July 18/19 Tenable scan #3833

**Closed by jason-upchurch** 2019-06-21 19:49 UTC
Labels: High priority
