### ISSUE TITLE
Remove 2-year restriction for CMS datatable schedule A

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2606] opened 2018-12-21 16:28 UTC
After removing the 2 year restriction from the API, we need to make a front-end change to remove the 2 year restriction from the CMS. We'll do this for just the schedule_a receipts first.

**Comment by lbeaufort** [comment] 2019-06-05 19:04
Duplicate of https://github.com/fecgov/fec-cms/issues/2811

**Closed by lbeaufort** 2019-06-05 19:04 UTC
Labels: Work: Front-end
