### ISSUE TITLE
Raw filings committee name or ID filter doesn’t work

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#5193] opened 2022-05-04 00:20 UTC
As a data user, I want to be able to search raw filings by name or ID. 

### Summary

I search for filing, specifically a Form 1, by name. The filter was not applied to the data returned in the data table. The name search doesn’t seem to work for first filings until after the nightly update. 

Filter: committee name or ID

**Action items:**
- [ ] Check the API first to see if that's where this issue originates. 
- [ ] Check with database team to see if we've been doing our routine cleaning

**Completion criteria:**
- [ ] Filter applies correctly

### Frequency
_an ongoing issue,_

### How to Reproduce

URL: https://www.fec.gov/data/filings/?data_type=efiling

C00814277 filed its Form 1 at 8:01 pm on 05/02/2022. (Filed too late to make it into the nightly update Monday night)

1. Searched for “queer-trans” on May 3. The filter was not applied to the data table. 
2. Searched for C00814277 on May 3. The filter was not applied to the data table. 

I’m mostly concerned about the name search.

![C7341D8B-FF08-4ADE-BFFC-EE5310DF9B80](https://user-images.githubusercontent.com/11817734/166606012-5d8de9b7-36cc-4ac8-ba27-ef35b36cf22a.png)
![01A10029-D0A5-43A0-9F70-A426F19FF856](https://user-images.githubusercontent.com/11817734/166606016-34895898-bc35-4ab0-8fb9-126dde83f042.png)

**Comment by patphongs** [comment] 2022-05-16 16:51
@PaulClark2 This ticket is related to this one that I've put in a comment for: https://github.com/fecgov/fec-cms/issues/5146#issuecomment-1127898776. It comes down to expected behavior of the text fields. If we choose it from the autosuggest itself, something comes up, however, if just doing a keyword search, the filter won't work. I think that's by design? But I'm not sure what's expected.

**Comment by PaulClark2** [comment] 2022-05-16 17:12
This feedback, https://github.com/fecgov/FEC/issues/11712, prompted my ticket. I'm not sure what the expected behavior is, but there's no indication on the filter or the data table that a someone searching for a new committee on the raw filings page might not be able to find that committee until after it's filing goes through nightly processing. My understanding is autosuggest only includes committees that have gone through autosuggest. In the example that prompted my ticket, the committee's F1 had not gone through nightly processing.

**Comment by JonellaCulmer** [comment] 2022-05-17 18:50
Closing in favor of https://github.com/fecgov/fec-cms/issues/5227

**Closed by JonellaCulmer** 2022-05-17 18:50 UTC
Labels: Bug, Needs refinement
